site_name: 'A collection of best practices and stuff'
site_url: 'https://toeggel.github.com/ReadTheDocs/index.html'
nav:
- Home: 'index.md'
- Architecture:
  - 'architecture/architect.md'
  - 'architecture/architecture.md'
  - 'architecture/c4.md'
  - 'architecture/caching.md'
  - 'architecture/database.md'
  - 'architecture/lightweight.md'
  - 'architecture/microservice.md'
  - 'architecture/misc.md'
  - 'architecture/onion.md'
  - 'architecture/patterns.md'
  - 'architecture/self-contained-systems.md'
  - 'architecture/service-bus.md'
  - 'architecture/tools.md'
  - 'architecture/uow.md'
  - 'architecture/vertical-slice.md'
- Azure: 
  - 'azure/azure.md'
  - 'azure/app-insights.md'
- C#: 
  - 'dot-net/const-static-readonly.md'
  - 'dot-net/functional-approach.md'
  - 'dot-net/enum-handling.md'
  - 'dot-net/record-types.md'
- Frontend:
  - 'Angular':
    - 'frontend/angular/index.md'
    - 'frontend/angular/angular-elements.md'
    - 'frontend/angular/data-load.md'
    - 'frontend/angular/error-handling.md'
    - 'frontend/angular/misc.md'
    - 'frontend/angular/modules.md'
    - 'frontend/angular/routed-component-input.md'
    - 'frontend/angular/structoring-components.md'
    - 'frontend/angular/take-until-destroyed.md'
  - 'JS': 
    - 'Firebase': 'frontend/js/firebase.md'
    - 'frontend/js/ngrx-push.md'
    - 'frontend/js/ngrx.md'
    - 'Rxjs': 'frontend/js/rxjs.md'
  - 'frontend/best-practices.md'
  - 'Css': 'frontend/css.md'
  - 'HTML5': 'frontend/html5.md'
  - 'Misc': 'frontend/misc.md'
  - 'Snippets': 'frontend/snippets.md'
  - 'frontend/typescript.md'
- Misc:
  - 'misc/beautiful-code.md'
  - 'misc/clean-code.md'
  - 'misc/dev-ops.md'
  - 'git': 'misc/git.md'
  - 'GitHub': 'misc/github.md'
  - 'Giving Feedback': 'misc/giving-feedback.md'
  - 'Misc': 'misc/misc.md'
  - 'Obsidian': 'misc/obsidian.md'
  - 'Pitch': 'misc/pitch.md'
  - 'misc/power-point.md'
  - 'REST': 'misc/rest.md'
  - 'Testing': 'misc/testing.md'
- About: 'about.md'
theme: 
  name: material
  # name: readthedocs
  # name: mkdocs

  features:
    - navigation.indexes
  palette:
  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
plugins:
  - search 
  - tags
  - callouts
markdown_extensions:
  - nl2br
  - admonition
  - pymdownx.details
  - pymdownx.superfences
    
  