site_name: 'A collection of best practices and stuff'
site_url: 'https://toeggel.github.com/ReadTheDocs/index.html'
nav:
- About: 'index.md'
- Architecture:
  - 'architecture/architect.md'
  - 'architecture/architectural-decision-records.md'
  - 'architecture/architecture-documentation.md'
  - 'architecture/architecture.md'
  - 'architecture/c4.md'
  - 'architecture/caching.md'
  - 'architecture/components.md'
  - 'architecture/database.md'
  - 'architecture/isaqb.md'
  - 'architecture/lightweight.md'
  - 'architecture/microservice.md'
  - 'architecture/misc.md'
  - 'architecture/monolith.md'
  - 'architecture/onion.md'
  - 'architecture/patterns.md'
  - 'architecture/resilience.md'
  - 'architecture/self-contained-systems.md'
  - 'architecture/service-bus.md'
  - 'architecture/tools.md'
  - 'architecture/unit-of-work.md'
  - 'architecture/vertical-slice.md'
  - 'architecture/whiteboard-model.md'
- Cloud:
  - 'cloud/logging.md'
  - 'cloud/azure-functions.md'
  - 'cloud/azure-services.md'
- Backend: 
  - 'backend/build-versions.md'
  - 'backend/const-static-readonly.md'
  - 'backend/entity-framework.md'
  - 'backend/enum-handling.md'
  - 'backend/functional-approach.md'
  - 'backend/record-types.md'
- Frontend:
  - 'frontend/blazor.md'
  - 'frontend/buttons-vs-links.md'
  - 'Angular':
    - 'frontend/angular/index.md'
    - 'frontend/angular/angular-elements.md'
    - 'frontend/angular/data-load.md'
    - 'frontend/angular/error-handling.md'
    - 'frontend/angular/misc.md'
    - 'frontend/angular/modules.md'
    - 'frontend/angular/routed-component-input.md'
    - 'frontend/angular/structoring-components.md'
    - 'frontend/angular/take-until-destroyed.md'
  - 'JS': 
    - 'Firebase': 'frontend/js/firebase.md'
    - 'frontend/js/ngrx-push.md'
    - 'frontend/js/ngrx.md'
    - 'Rxjs': 'frontend/js/rxjs.md'
  - 'frontend/best-practices.md'
  - 'Css': 'frontend/css.md'
  - 'HTML5': 'frontend/html5.md'
  - 'Misc': 'frontend/misc.md'
  - 'Snippets': 'frontend/snippets.md'
  - 'frontend/typescript.md'
- Misc:
  - 'misc/beautiful-code.md'
  - 'misc/clean-code.md'
  - 'misc/containerization.md'
  - 'misc/dev-ops.md'
  - 'git': 'misc/git.md'
  - 'GitHub': 'misc/github.md'
  - 'Giving Feedback': 'misc/giving-feedback.md'
  - 'Misc': 'misc/misc.md'
  - 'Obsidian': 'misc/obsidian.md'
  - 'Pitch': 'misc/pitch.md'
  - 'misc/power-point.md'
  - 'misc/raspberry-pi.md'
  - 'REST': 'misc/rest.md'
  - 'Testing': 'misc/testing.md'
  - 'misc/uBlock.md'
  - 'misc/validation.md'
theme: 
  name: material
  # name: readthedocs
  # name: mkdocs

  features:
    - navigation.indexes
  palette:
  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: custom
    accent: custom
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
extra_css:
  - stylesheets/theme.css
  - stylesheets/extra.css
plugins:
  - search 
  - tags
  - callouts
markdown_extensions:
  - nl2br
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
        # make exceptions to highlighting of code:
      custom_fences:
        # Mermaid diagrams
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  