site_name: My Docs
nav:
- Home: 'index.md'
- C#: 
  - 'dotNet/constStaticReadonly.md'
  - 'Functional Approach': 'dotNet/functionalApproach.md'
- Frontend:
  - 'Css': 'frontend/css.md'
  - 'JS': 'frontend/index.md'
  - 'Snippets': 'frontend/snippets.md'
- Misc:
  - 'Writing Beatiful Code': 'misc/beautifulCode.md'
  - 'GitHub': 'misc/github.md'
  - 'Pitch': 'misc/pitch.md'
- About: 'about.md'
theme: 
    name: readthedocs
    # name: mkdKocs