site_name: My Docs
nav:
- Home: 'index.md'
- C#: 
  - 'dotNet/constStaticReadonly.md'
  - 'Functional Approach': 'dotNet/functionalApproach.md'
- About: 'about.md'
theme: 
    # name: readthedocs
    name: mkdocs