site_name: 'A collection of best practices and stuff'
site_url: 'https://toeggel.github.com/ReadTheDocs/index.html'
nav:
- Home: 'index.md'
- Architecture:
  - 'architecture/architecture.md'
  - 'architecture/c4.md'
  - 'architecture/database.md'
  - 'architecture/lightweight.md'
  - 'architecture/microservices.md'
  - 'architecture/misc.md'
  - 'architecture/onion.md'
  - 'architecture/saga.md'
  - 'architecture/service-bus.md'
  - 'architecture/software-architect.md'
  - 'architecture/tools.md'
  - 'architecture/uow.md'
  - 'architecture/vertical-slice.md'
- Azure: 
  - 'azure/azure.md'
  - 'azure/app-insights.md'
- C#: 
  - 'dotNet/constStaticReadonly.md'
  - 'Functional Approach': 'dotNet/functionalApproach.md'
  - 'Enum Handling': 'dotNet/enumHandling.md'
  - 'Record Types': 'dotNet/recordTypes.md'
- Frontend:
  - 'frontend/best-practices.md'
  - 'Css': 'frontend/css.md'
  - 'HTML5': 'frontend/html5.md'
  - 'JS': 
    - 'Rxjs': 'frontend/js/rxjs.md'
    - 'NgRx': 'frontend/js/ngrx.md'
    - 'Firebase': 'frontend/js/firebase.md'
  - 'Angular': 
    - 'frontend/angular/structoring-components.md'
    - 'frontend/angular/angular-elements.md'
    - 'frontend/angular/data-load.md'
    - 'frontend/angular/misc.md'
  - 'Snippets': 'frontend/snippets.md'
  - 'Misc': 'frontend/misc.md'
- Misc:
  - 'Writing Beatiful Code': 'misc/beautifulCode.md'
  - 'misc/clean-code.md'
  - 'misc/power-point.md'
  - 'GitHub': 'misc/github.md'
  - 'REST': 'misc/rest.md'
  - 'Pitch': 'misc/pitch.md'
- About: 'about.md'
theme: 
    name: material
    # name: readthedocs
    # name: mkdocs
  