site_name: 'A collection of best practices and stuff'
docs_dir: src
site_dir: 'docs'
nav:
- Home: 'index.md'
- Architecture:
  - 'architecture/architecture.md'
  - 'architecture/microservices.md'
  - 'architecture/database.md'
- Azure: 
  - 'azure/azure.md'
- C#: 
  - 'dotNet/constStaticReadonly.md'
  - 'Functional Approach': 'dotNet/functionalApproach.md'
- Frontend:
  - 'Css': 'frontend/css.md'
  - 'JS': 'frontend/index.md'
  - 'Snippets': 'frontend/snippets.md'
- Misc:
  - 'Writing Beatiful Code': 'misc/beautifulCode.md'
  - 'GitHub': 'misc/github.md'
  - 'REST': 'misc/rest.md'
  - 'Pitch': 'misc/pitch.md'
- About: 'about.md'
theme: 
    name: material
    # name: readthedocs
    # name: mkdocs
  