site_name: 'A collection of best practices and stuff'
site_url: 'https://toeggel.github.com/ReadTheDocs/index.html'
theme: 
  name: material
  # name: readthedocs
  # name: mkdocs

  features:
    - navigation.indexes
  palette:
  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: custom
    accent: custom
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
extra_css:
  - stylesheets/theme.css
  - stylesheets/extra.css
plugins:
  - search 
  - tags
  - callouts
markdown_extensions:
  - nl2br
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
        # make exceptions to highlighting of code:
      custom_fences:
        # Mermaid diagrams
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  